# Generated by Django 5.1.1 on 2025-11-25 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Additional event photo for media (Recommended: 800x600px, Max: 5MB)', upload_to='events/media/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, help_text='Optional description for this image', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event Image',
                'verbose_name_plural': 'Event Images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a catchy title for your event', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Detailed description of your event')),
                ('main_image', models.ImageField(blank=True, help_text='Main event banner image (Recommended: 1200x600px, Max: 5MB)', null=True, upload_to='events/main_images/%Y/%m/%d/', verbose_name='Main Event Image')),
                ('thumbnail', models.ImageField(blank=True, help_text='Event thumbnail for cards and lists (Recommended: 400x300px, Max: 2MB)', null=True, upload_to='events/thumbnails/%Y/%m/%d/', verbose_name='Event Thumbnail')),
                ('image', models.ImageField(blank=True, help_text='Original event image (fallback)', null=True, upload_to='events/original/%Y/%m/%d/', verbose_name='Event Image')),
                ('date', models.DateField(help_text='Date when the event will take place')),
                ('time', models.TimeField(help_text='Start time of the event')),
                ('location', models.CharField(help_text='Venue or online location', max_length=300)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Ticket price in Rs.', max_digits=10)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of attendees')),
                ('is_active', models.BooleanField(default=True, help_text='Make event visible to public')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this event on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='categories.tag')),
                ('gallery_images', models.ManyToManyField(blank=True, help_text='Additional images for event media', related_name='events', to='events.eventimage')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='events_even_created_7af6de_idx'), models.Index(fields=['is_active', 'is_featured'], name='events_even_is_acti_d60ef6_idx'), models.Index(fields=['date', 'time'], name='events_even_date_3a55f7_idx')],
            },
        ),
    ]
