# Generated by Django 5.1.1 on 2025-11-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter category name (e.g., Music, Sports, Business)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name (auto-generated)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the category')),
                ('image', models.ImageField(blank=True, help_text='Upload category image (Recommended: 400x300 pixels, Max: 2MB)', null=True, upload_to='categories/%Y/%m/%d/', verbose_name='Category Image')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable category visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter tag name (e.g., concert, workshop, free)', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the tag name', unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the tag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
